name: Ruby Gem2

on:
  workflow_dispatch:
    inputs:
      otp:
        description: "One-time password for RubyGems.org"
        required: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build + test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JRuby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: bundle install
    - run: gem install rspec
    - name: test
      run: |
        gem build *.gemspec
        gem install *.gem
        rspec sample/samplez.rb
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: bundle install

    - name: build gem
      run: |
        ruby -S gem build *.gemspec

#    - name: Publish to GPR
#      run: |
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        ruby -S gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
#      env:
#        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
#        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        cat << EOF > > $HOME/.gem/credentials
        ---
        github: Bearer ${GITHUB_TOKEN}
        rubygems_api_key: ${GEM_HOST_API_KEY}
        EOF
        chmod 0600 $HOME/.gem/credentials
        ruby -S gem push --otp ${GEM_HOST_OTP_CODE} *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        GEM_HOST_OTP_CODE: "${{ inputs.otp }}"
        GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}}
