name: Ruby Gem

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build + test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
# Java 21 を使えるようにする
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: oracle

    - name: Set up JRuby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: bundle install
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GITHUB_TOKEN }}
    - run: gem install rspec
    - name: test
      run: |
        gem build *.gemspec
        gem install *.gem
        cd sample
        rake -f act.rk spec
 
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: bundle install

#    - name: Publish to GPR
#      run: |
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        ruby -S gem build *.gemspec
#        ruby -S gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
#      env:
#        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
#        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
         curl --data-binary @gemcutter-0.2.1.gem \
              -H 'Authorization:${GEM_HOST_API_KEY}' \
              -H 'OTP:${GEM_GITHUB_KEY}' \
              https://rubygems.org/api/v1/gems
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        gem build *.gemspec
#        gem push --key github *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        GEM_GITHUB_KEY: "${{secrets.GITHUB_TOKEN}}"
